### ISSUE TITLE
Goat Disappeared 

### ISSUE THREAD

**Issue by NyxKhaos** [Pingu-Pox/duncraft-reborn#26] opened 2022-10-16 07:59 UTC
Right after server update at 2:30am 10/16/22. I went back into the area where I had my goat stored and it was gone. No lasso on the floor either. There is nothing that could of killed it. Goat was there all day since I found it maybe 12 hours prior and it never got loose and no mobs have ever spawned in that area. I turned around to leave the room where I was growing my stuff and thats when I noticed it was gone and that it was so quiet, cause it was pretty loud and made noise often.

**Comment by Pingu-Pox** [comment] 2022-10-20 03:52
Duplicate of #23

**Closed as completed by Pingu-Pox** 2022-10-20 03:52 UTC
