### ISSUE TITLE
Seed Analyzer crashes when activated 

### ISSUE THREAD

**Issue by torinnramheart** [Pingu-Pox/duncraft-reborn#9] opened 2022-08-18 01:24 UTC
**Describe the bug**
My game crashes when I use the seed analyzer

**To Reproduce**
1. go to a seed analyzer
2. press right click on it
3. ????
4. Profit

**Expected behavior**
Open the GUI for seed analyzer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 1.18.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pingu-Pox** [comment] 2022-08-19 05:33
Crash caused by interaction between Agricraft and Pehkui. Considering options.

**Comment by Pingu-Pox** [comment] 2022-08-19 16:22
More information on the issue:
https://github.com/AgriCraft/AgriCraft/issues/1463
https://github.com/InfinityRaider/InfinityLib/issues/18

Will need to ditch Agricraft or Pehkui.

**Comment by Pingu-Pox** [comment] 2022-08-19 20:52
Pehkui was updated a few days ago, contains a fix for this bug. Tested and no longer an issue. Live in 0.1.8

**Closed as completed by Pingu-Pox** 2022-08-19 20:52 UTC
